-- MySQL Script generated by MySQL Workbench

-- vie 11 nov 2016 11:09:23 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema apoyos_usuarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apoyos_usuarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apoyos_usuarios` DEFAULT CHARACTER SET utf8 ;
USE `apoyos_usuarios` ;

-- -----------------------------------------------------
-- Table `apoyos_usuarios`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apoyos_usuarios`.`usuarios` (
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_p` VARCHAR(45) NOT NULL,
  `apellido_m` VARCHAR(45) NOT NULL,
  `activo` INT NOT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apoyos_usuarios`.`catalogo_sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apoyos_usuarios`.`catalogo_sucursales` (
  `id_sucursal` INT NOT NULL,
  `region` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apoyos_usuarios`.`catalogo_operacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apoyos_usuarios`.`catalogo_operacion` (
  `id_operacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_operacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apoyos_usuarios`.`apoyos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apoyos_usuarios`.`apoyos` (
  `id_apoyos` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `id_usuario` VARCHAR(45) NOT NULL,
  `actividad_realizada` INT NOT NULL,
  `sucursal` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `usuario_soporte` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_apoyos`),
  INDEX `fk_apoyos_usuarios_idx` (`usuario_soporte` ASC),
  CONSTRAINT `fk_apoyos_usuarios`
    FOREIGN KEY (`usuario_soporte`)
    REFERENCES `apoyos_usuarios`.`usuarios` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
